### ISSUE TITLE
Output - parte 2

### ISSUE THREAD

**Issue by lzanol** [sambatech/player_sdk_ios#16]
- [x] Layout menu
- [x] Trocar output

Sugestão: 2 modais diferentes para fs on e off. Não permitir a mudança de orientação quando tiver com ele aberto ( comportamento parecido com o do youtube )

**Comment by priscilamagalhaes** [comment]
### BUGS

- [ ] Listagem de outputs está apresentando linhas extras, dando a impressão que teriam outras opções que não foram carregadas
![img_0071](https://cloud.githubusercontent.com/assets/10501332/17178573/68d55cce-53ec-11e6-99f2-470a57d277d6.PNG)

**Comment by ThiagoMiranda** [comment]
Sugestões:
- Não deixar o usuário trocar de output no carregamento do vídeo
- Tentar colocar um height fixo na listagem ( x% do tamanho total da tela? )
