### ISSUE TITLE
IMA - parte 2

### ISSUE THREAD

**Issue by lzanol** [sambatech/player_sdk_ios#17]
Parte 1
- [x] Validar/consertar cenários com problemas - 1
- [x] Testes - 1
- [x] Envio ao google

Parte 2
- [x] VastTag via API - 2
- [x] Testes - 1

**REFS**

https://developers.google.com/interactive-media-ads/compatibility

**Comment by priscilamagalhaes** [comment]
### BUGS

- [ ] Está apresentando barra de seek ao retornar ao player após acessar o site da publicidade
![img_0070](https://cloud.githubusercontent.com/assets/10501332/17178165/c08bedd6-53ea-11e6-80b9-ccc111f4d8c5.PNG)

**Comment by priscilamagalhaes** [comment]
## Evidências

![img_0067](https://cloud.githubusercontent.com/assets/10501332/17178183/ccd1db8c-53ea-11e6-84a5-1ea54464c0e7.PNG)

**Comment by priscilamagalhaes** [comment]
https://api.myjson.com/bins/34knr
