### ISSUE TITLE
Criação da área de Live

### ISSUE THREAD

**Issue by priscilamagalhaes** [sambatech/player_sdk_ios#19]
- [x] Criação da área de Live (sample app)
- [x] Layout live
- [x] Exemplos de Live ( 3 )
- [x] Testes

**Comment by priscilamagalhaes** [comment]
Inserir live de audio
autoStart=true&alternateLive=http://slrp.sambavideos.sambatech.com/radio/pajucara4_7fbed8aac5d5d915877e6ec61e3cf0db/livestream/playlist.m3u8&type=AUDIOLIVE&gaAccount=UA-2685561-12&streamName=radio103&volume=25

**Comment by ThiagoMiranda** [comment]
Vou verificar

**Comment by ThiagoMiranda** [comment]
Ps: há um bug que no Live ao clicar pause e voltar o tempo volta pro zero. Poderiamos colocar uma issue disso mas como prioridade baixa

**Comment by priscilamagalhaes** [comment]
![img_0072](https://cloud.githubusercontent.com/assets/10501332/17187502/e53ca3ee-540f-11e6-9c27-007b0166bd6c.PNG)
