### ISSUE TITLE
Player AUDIO

### ISSUE THREAD

**Issue by priscilamagalhaes** [sambatech/player_sdk_ios#21]
- [x] Tocar mídia áudio ou vídeo - 1
- [x] Diminuir player para proporções áudio ( remover controles desnecessários ) - 1 
- [x] Testes - 1 

DONE: Player de áudio no iOS

**Comment by priscilamagalhaes** [comment]
### BUGS

- [ ] Após finalizar o aúdio e clicar em Play não está reiniciando a mídia.

**Comment by ThiagoMiranda** [comment]
Sugestões:
- Provavelmente ele conta com o click no "reload". Mudar o botão de player para reload e adicionar um trigger nele?

**Comment by ThiagoMiranda** [comment]
- [ ] Controles do áudio não funcionando
- [ ] Interação do reload após o áudio estiver terminado
