### ISSUE TITLE
Erro no carthage

### ISSUE THREAD

**Issue by aleufms** [sambatech/player_sdk_ios#29]
Está dando o seguinte erro no carthage update:

> output /Users/an/Developer/meSalva/Carthage/Build/iOS/SambaPlayer.framework/SambaPlayer) failed with exit code 1:
> fatal error: /Applications/Xcode 7.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: /Users/an/Library/Developer/Xcode/DerivedData/SambaPlayer-cnvaczupudikotcbsrobgtgyscca/Build/Products/Release-iphoneos/SambaPlayer.framework/SambaPlayer and /Users/an/Library/Developer/Xcode/DerivedData/SambaPlayer-cnvaczupudikotcbsrobgtgyscca/Build/Products/Release-iphonesimulator/SambaPlayer.framework/SambaPlayer have the same architectures (i386) and can't be in the same fat output file

Alguém sabe como resolver? Valeu.

**Comment by lzanol** [comment]
Olá @aleufms, se o erro ocorreu na **primeira vez** que você executou `carthage update`, pode ser algo relacionado à versão da ferramenta `lipo`. Tente verificar qual das versões está sendo usada (do OS ou do Xcode): http://stackoverflow.com/a/18993368/3688598

Caso já tenho funcionado anteriormente, tente limpar a cache do Carthage e executar `carthage update` novamente:
```sh
rm -rf Cartfile.resolved
rm -rf Carthage/
rm -rf ~/Library/Caches/org.carthage.CarthageKit/
```

**Comment by aleufms** [comment]
Para isolar o erro eu estou fazendo um projeto sem nada, somente com carthage. Meu Xcode é o 7 (ainda não posso migrar para o 8). Já atualizei meu sistema para o Sierra.

É a primeira vez que uso o carthage (uso o Cocoapods normalmente) então pode ser alguma noobisse minha. Mas eu testei instalando o SwiftyJSON e o Alamofire e foram suave. Limpei o cache como você disse, ainda sem sucesso. O lint ele usa do Xcode 7.3.1.

**Comment by lzanol** [comment]
Ainda não fizemos testes com o Sierra, somente no El Capitan. Pode de fato ter algo a ver com a versão do `lipo` do OS, pois ele é usado em um script nosso executado junto ao `carthage update`.

Uma alternativa no momento (sendo este de fato o caso), seria "apontar" a versão do OS (e.g. `/usr/bin/lipo`) para a versão contida em seu Xcode (e.g. `/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo`) e veja se resolve o problema.

Ex.: `sudo ln -s /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo /usr/local/bin/lipo`

Em teoria o `carthage update` dará preferência à versão contida em seu `local`.

**Comment by aleufms** [comment]
Tentei usar o lipo do Xcode 8 e deu o seguinte erro:

Vocês chegaram a testar no Xcode 8?

> The following build commands failed:
> 	Check dependencies
> (1 failure)
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 	Check dependencies
> (1 failure)
> A shell task (/usr/bin/xcrun xcodebuild -project /Users/an/Developer/meSalva/Carthage/Checkouts/player_sdk_ios/SambaPlayer.xcodeproj -scheme SambaPlayer -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
> ** CLEAN FAILED **
> 
> 
> The following build commands failed:
> 	Check dependencies
> (1 failure)
> ** BUILD FAILED **
> 
> 
> The following build commands failed:
> 	Check dependencies
> (1 failure)

**Comment by lzanol** [comment]
Ainda não testamos com Xcode 8, somente o 7. Tente fazer o teste com o `lipo` do Xcode 7 como comentei.

Quanto ao Xcode 8, você pode tentar configurar o compilador Swift para suportar código legado (utilizamos Swift 2.3):

`Use Legacy Swift Language Version: Yes`

De qualquer modo, estamos concluindo a conversão para Swift 3, o que deve resolver os problemas com o Xcode 8.

**Comment by aleufms** [comment]
Sim, os primeiros erros que eu enviei são com o Xcode 7. O lipo do "/usr/bin/lipo" já está apontando para o do Xcode 7(/Applications/Xcode 7.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo).

Não tem jeito de você disponibilizar o fat framework já compilado?

**Comment by lzanol** [comment]
É um pouco perigoso, pois pode ocorrer alguma falha de compatibilidade de hardware, etc. Por isso o Carthage utiliza a própria máquina do usuário para fazer o build:
> The Swift debugger can crash when stopping in code that depends on a Swift library or framework that has been distributed in binary form.
>
> Frameworks written in Swift should be compiled from source as part of the same project that depends on them to guarantee a single, consistent compilation environment. (22492040)

https://developer.apple.com/library/content/documentation/Xcode/Conceptual/RN-Xcode-Archive/Chapters/xc7_release_notes.html

**Comment by lzanol** [comment]
Nesse caso, você pode tentar gerar a versão universal (fat binary) e contornar o primeiro erro ocorrido (de sobrescrever o arquivo de origem com o arquivo de saída, certo?):
```sh
lipo -create lib_archset1 lib_archset2 -o lib_universal
lipo -info lib #i386 x86_64 arm64 armv7 armv7s

# Keep only architectures for project:
pathArchs=()
for arch in ${project_archs} do
	lipo -extract arch lib_universal -o lib_specified_arch-arch
	pathArchs+=("lib_specified_arch-arch")
done
lipo -create "${pathArchs[@]}" -o lib_project_archs
```
Caso tenha alguma dúvida, este artigo abaixo explica bem (ou me pergunte 😄 ):
http://ikennd.ac/blog/2015/02/stripping-unwanted-architectures-from-dynamic-libraries-in-xcode/

**Comment by lzanol** [comment]
@aleufms Não havia percebido anteriormente, mas parece ter um problema no build. Ele deveria gerar uma versão para o simulator (arquiteturas i386 e x86_64) e outra para o dispositivo (arquiteturas arm64 armv7/armv7s). Aí então entraria o `lipo` para mesclar as duas e gerar a versão universal. Mas de fato parece que o build gerou duas versões idênticas!

Nesse sentido, tente verificar se tem algum problema no compilador usado pelo Xcode 7. E a configuração que sugeri com o Xcode 8 (acima) funcionou?

**Comment by dogczar** [comment]
Tento buildar como na documentação e recebo o seguinte erro : 

RP10727-Renan:player_sdk_ios_sample_app renanjunior$ carthage update
*** Cloning player_sdk_ios
*** Checking out player_sdk_ios at "v0.1.8"
*** xcodebuild output can be found in /var/folders/9s/l5x4tbtx4kvb6pz65d9vcvg80000gp/T/carthage-xcodebuild.L2pWS1.log
*** Building scheme "SambaPlayer" in SambaPlayer.xcodeproj
** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -project /Users/renanjunior/player_sdk_ios_sample_app/Carthage/Checkouts/player_sdk_ios/SambaPlayer.xcodeproj -scheme SambaPlayer -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)

Voce pode me ajudar ?

**Comment by lzanol** [comment]
Olá @dogczar, qual versão do Xcode você está utilizando?

**Comment by dogczar** [comment]
É a 8.

Em qui, 20 de out de 2016 14:47, Leandro Zanol <notifications@github.com>
escreveu:

**Comment by dogczar** [comment]
Olá Leandro !

tem alguma solução para o meu caso ?

Abraços,
Renan Junior

**Comment by lzanol** [comment]
@dogczar Entendi. Infelizmente nossa [última versão em produção](https://github.com/sambatech/player_sdk_ios/releases/tag/v0.1.8) foi homologada somente para Xcode 7 e Swift 2/Objective-C.

Iremos atualizar outra versão em breve com suporte ao Xcode 8 e Swift 3/Objective-C.

**Comment by AlbertoLourenco** [comment]
Olá, pessoal.

Estou passando pelo mesmo problema, vocês já conseguiram resolver?

Obrigado.

**Comment by ThiagoMiranda** [comment]
@AlbertoLourenco tudo bem? Qual versão você está usando no se Cartfile?

**Comment by gabrielvieira** [comment]
@ThiagoMiranda @AlbertoLourenco tentamos usar a versão 0.2.0 e 0.2.1 e não conseguimos buildar

**Comment by ThiagoMiranda** [comment]
@AlbertoLourenco @gabrielvieira teria como confirmar o conteúdo da pasta Carthage/Build/iOS ?
Obrigado

**Comment by gabrielvieira** [comment]
Ele gera os dois arquivos porém da fatal error na build

![captura de tela 2016-12-09 as 14 33 20](https://cloud.githubusercontent.com/assets/4401695/21056370/7d745532-be1c-11e6-9cee-84d5b68feb29.png)

**Comment by ThiagoMiranda** [comment]
Vamos investigar aqui @gabrielvieira . Assim que tiver uma novidade avisamos.

**Comment by gabrielvieira** [comment]
@ThiagoMiranda Beleza, obrigado

**Comment by ThiagoMiranda** [comment]
@gabrielvieira @AlbertoLourenco 
Temos um "known issue" hoje no passo `carthage update` ( ou `carthage build` ) onde nosso script é rodado 2 vezes. Na segunda ele da um fatal erro exatamente por já ter rodado mas não influencia no funcionamento. Continua funcionando.

A versão 0.2.+ do player só funciona a partir do Xcode8 por usar o Swift 3. Teria como nos confirmar exatamente em que passo está dando o erro?
Nos nossos testes internos conseguimos rodar. Lembrando sempre que é preciso fazer os passos do README.MD depois do carthage update/build. 

Obrigado.

**Comment by gabrielvieira** [comment]
@ThiagoMiranda  Os passos do header já estão feitos, dei build novamente e atualizei no projeto, está retornando esse erro: 
![captura de tela 2016-12-09 as 18 15 43](https://cloud.githubusercontent.com/assets/4401695/21063221/a439a70c-be3b-11e6-8109-91a667d2f525.png)

Estou no El Captan, Xcode 8.1

**Comment by ThiagoMiranda** [comment]
Boa tarde @gabrielvieira . Teria como você dar um `lipo -info Carthage/Build/iOS/SambaPlayer.framework/SambaPlayer` e confirmar as arquiteturas "buildadas"?
O output correto seria algo como:
`Architectures in the fat file: Carthage/Build/iOS/SambaPlayer.framework/SambaPlayer are: i386 x86_64 armv7 arm64 `

**Comment by ThiagoMiranda** [comment]
@gabrielvieira Uma outra sugestão seria uma limpeza nos arquivos do Xcode.
`Command + Option + Shift + K`
Limpa o diretório
`Command + Shift + K`
Limpa os arquivos que o xcode deixa pré compilado

Depois disso tente buildar novamente.

Obrigado

**Comment by gabrielvieira** [comment]
@ThiagoMiranda  segui os comandos que vc passou, ainda estou tendo o mesmo problema, no IOS 10.0.2 funcionou, no IOS 10 mais atualizado deu esse problema de incompatible version of swift, e no IOS 9 deu outro erro : lipo: -extract armv7 specified but fat file: /Users/gabriel/Library/Developer/Xcode/DerivedData/Univer-cspopudfevfnuzdjyhnebrrzpmbh/Build/Products/Debug-iphoneos/Univer.app/Frameworks/SambaPlayer.framework/SambaPlayer does not contain that architecture

**Comment by ThiagoMiranda** [comment]
@gabrielvieira Teria como confirmar o resultado do comando `lipo -info`?

De qualquer forma aparentemente é um problema específico de ambiente ( já que o binário não está completo ) que infelizmente não conseguimos reproduzir aqui na empresa. Os testes foram realizados com:
Xcode: 8.1 (8B62), 8.1 Beta
macOS: Sierra 10.12.1, El Captain 10.11.6
iPhone 5 (iOS: 10.1.1), iPhone 5s (iOS: 10.0.2) e nos simuladores disponíveis

Uma alternativa ( não recomendamos mas devido a urgência ) seria clonar o repositório localmente e referenciá-lo como fazemos em nosso Sample app ( arrastando o SambaPlayer.xcodeproj local para seu workspace )

https://github.com/sambatech/player_sdk_ios_sample_app

**Comment by gabrielvieira** [comment]
@ThiagoMiranda Architectures in the fat file: Carthage/Build/iOS/SambaPlayer.framework/SambaPlayer are: i386 x86_64 armv7 arm64

**Comment by ThiagoMiranda** [comment]
@gabrielvieira Mais um conselho. Teria como testar essa flag `Use Legacy Swift Language Version` como Yes?

`Project -> Targets -> Build Settings -> Use Legacy Swift Language Version `

**Comment by ThiagoMiranda** [comment]
@gabrielvieira só checando. Foram seguidos os passos do nosso https://github.com/sambatech/player_sdk_ios/blob/drm/README.md ? Obrigado

**Comment by gabrielvieira** [comment]
@ThiagoMiranda Consegui ultilzar, obrigado

**Comment by ThiagoMiranda** [comment]
@gabrielvieira Excelente cara =)
Teria como detalhar o que aconteceu? Pode nos ajudar no futuro.

**Comment by gabrielvieira** [comment]
@ThiagoMiranda Na troca de versão do swift2 para o swift3 ficou algum cache no projeto, e estava dano incompatibilidade de versões.

**Comment by ThiagoMiranda** [comment]
Obrigado @gabrielvieira . Vamos adicionar esse ponto de atenção em nossa documentação.
Qualquer coisa estamos a disposição.
