### ISSUE TITLE
Suporte a backupLive

### ISSUE THREAD

**Issue by ThiagoMiranda** [sambatech/player_sdk_ios#31]
### Tarefas
- [x] Alterar entidades
- [x] Fazer fallback
- [x] Incrementar versão (0.4.0) e build
- [x] Criar casos de teste
  - primaryLive funcionando
  - backupLive funcionando
  - os dois não funcionam
  - com ad_program - http://playerground.sambatech.com/live/pcases/4
  - com geobloqueio - http://playerground.sambatech.com/erros-player/pcases/6
  - exemplo HDS - http://playerground.sambatech.com/live/pcases/5
- [x] Instalar em device
- [x] Wiki
- [x] Class reference
- [x] Testes
- [ ] Publicar
### Artefatos de saída
- [Release](https://github.com/sambatech/player_sdk_ios/releases/tag/0.4.0)
- [Wiki](https://github.com/sambatech/player_sdk_ios/wiki/Guia-de-uso#fallback-live)
- [Class reference](http://dev.sambatech.com/documentation/iossdk/index.html): `SambaMediaRequest`, `SambaPlayerError`

**Comment by priscilamagalhaes** [comment]
### BUGS

 - [ ] Cenário Geoblocking não está executando. Obs.: no android executa
