### ISSUE TITLE
[BUG] Layout de erro de falha de conexão quebrado em telas menores

### ISSUE THREAD

**Issue by denisemaia** [sambatech/player_sdk_ios#45]
**Descrição:**
Foi verificado que o layout de erro de falha de conexão está quebrado em telas menores, como do iphone 5s:

![img_0275](https://user-images.githubusercontent.com/20074534/28216779-2f4f793c-6889-11e7-934e-9fa9f8482605.png)

**Versão SDK:**
0.6

**Dispositivo:**
iphone 5s

**Comment by lzanol** [comment]
Resolvido: ee7b1f1912a7e73b281b9c23ddce30a4fbc03321
