### ISSUE TITLE
[BUG] Duração de live não está mais sendo exibida na versão 0.8.1 do SDK

### ISSUE THREAD

**Issue by denisemaia** [sambatech/player_sdk_ios#51]
**Descrição:**
Foi verificado que a duração da Live não está mais sendo exibida na versão 0.8.1 do SDK, conforme versões anteriores.

**Versão SDK:** 0.8.1

**Aplicativo:** Samba Play App

**Comment by ThiagoMiranda** [comment]
Comportamento esperado
