### ISSUE TITLE
Documentação

### ISSUE THREAD

**Issue by lzanol** [sambatech/player_sdk_ios#6]
- [x] Suporte (Android 6.0, devices, etc.) - 1
- [x] Guia de Uso (incluindo informações sobre instalação, dependências e identificadores do repo Cocoapods que hospeda os artefatos) - 2
- [x] Release Notes - 1
- [x] Class Reference - 1
- [x] Wiki
- [x] Dev.docs

**DONE**

DevDocs documentando SDK com suporte (OS versions, API, devices, etc.), guia de uso, release notes e referência das classes, sendo suficiente para que um desenvolvedor consiga construir um aplicativo para um cliente Samba Videos apenas com base na leitura da mesma.

**REFS**

https://www.raywenderlich.com/66395/documenting-in-xcode-with-headerdoc-tutorial

http://stackoverflow.com/questions/24047991/does-swift-have-documentation-comments-or-tools

https://github.com/realm/jazzy

**Comment by ThiagoMiranda** [comment]
Possíveis ajudas

http://nshipster.com/swift-documentation/
https://github.com/realm/jazzy
