### ISSUE TITLE
[BUG] - Error to load media

### ISSUE THREAD

**Issue by maclacerda** [sambatech/player_sdk_ios#63]
Hi everyone,

I have an issue to starting loading media process, i'm using the same projectHash used on Android app and i'm using the fixed mediaID for validating my test. But, the SDK returns the follow stack trace, even that i change mediaID the problem continues.

Help me please!

Stack trace:

`SambaApi Requesting URL: https://fast.player.liquidplatform.com/pApiv2/v1/31044efbcb9b4ac1df2190f3e902e25f/27ee075e130a095d02de1005d0f80def
Helpers.Type Error: Invalid server response (<NSHTTPURLResponse: 0x60400023d2a0> { URL: https://fast.player.liquidplatform.com/pApiv2/v1/31044efbcb9b4ac1df2190f3e902e25f/27ee075e130a095d02de1005d0f80def } { Status Code: 500, Headers {
    Age =     (
        100
    );
    "Content-Type" =     (
        "application/json;charset=UTF-8"
    );
    Date =     (
        "Tue, 30 Jan 2018 14:54:28 GMT"
    );
    Server =     (
        "nginx/1.8.0"
    );
    Via =     (
        "1.1 d2c636aea3f69033bb2125c4038e1c49.cloudfront.net (CloudFront)"
    );
    "x-amz-cf-id" =     (
        "CU8tUph8c6BzhvNoc5D9XCDauknTPcDBwJ23DV6Yoo6T2a9d1mjI3w=="
    );
    "x-cache" =     (
        "Error from cloudfront"
    );
    "x-cnection" =     (
        close
    );
} }).
https://fast.player.liquidplatform.com/pApiv2/v1/31044efbcb9b4ac1df2190f3e902e25f/27ee075e130a095d02de1005d0f80def
Method: GET
Header: nil`

My media request:

`SambaApi().requestMedia(SambaMediaRequest(projectHash: kProjectHash, mediaId: mediaID), onComplete: { (media: SambaMedia?) in
            guard let media = media else {
                handler(nil, \"Error to loading media.\")
                return
            }
            
            handler(media, nil)
        }) { (errorResponse, _) in
            if let error = errorResponse {
                handler(nil, error.localizedDescription)
            } else {
                handler(nil, \"Error to loading media.\")
            }
        }`

Thanks for your help

**Comment by marcoslacerda** [comment]
My media request:

`SambaApi().requestMedia(SambaMediaRequest(projectHash: kProjectHash, mediaId: mediaID), onComplete: { (media: SambaMedia?) in
            guard let media = media else {
                handler(nil, \"Error to loading media.\")
                return
            }
            
            handler(media, nil)
        }) { (errorResponse, _) in
            if let error = errorResponse {
                handler(nil, error.localizedDescription)
            } else {
                handler(nil, \"Error to loading media.\")
            }
        }`
