### ISSUE TITLE
[QUESTION] - Alterar cor da seekbar e progress

### ISSUE THREAD

**Issue by marcoslacerda** [sambatech/player_sdk_ios#66]
Boa tarde,

É possível alterar as cores da seekbar de um vídeo e da progress de loading do mesmo?

Grato

**Comment by lzanol** [comment]
Olá @marcoslacerda, para alterar as cores do tema basta modificar o código de cor na entidade de configurações (`SambaMedia`) antes de enviá-la ao player. Segue um exemplo em **Swift**:
```swift
let request = SambaMediaRequest(projectHash: "...", mediaId: "...")
let api = SambaApi()

api.requestMedia(request) { (media: SambaMedia?) in
	guard let media = media else { return }

	let sambaPlayer = SambaPlayer(parentViewController:self)
	media.theme = 0xFF996633
	sambaPlayer.media = media
	sambaPlayer.play()
}
```
**Documentação com exemplo de alteração da cor**
https://github.com/sambatech/player_sdk_ios/wiki/Guia-de-uso#exemplo-de-uso-m%C3%ADdia-externa

**Documentação de exemplo com Samba Videos**
https://github.com/sambatech/player_sdk_ios/wiki/Guia-de-uso#exemplo-de-uso-samba-videos-api

**Comment by marcoslacerda** [comment]
Obrigado!
