### ISSUE TITLE
Deployment - 8

### ISSUE THREAD

**Issue by ThiagoMiranda** [sambatech/player_sdk_ios#8]
- [x] Empacotar o sdk em um framework 3
- [x] Estudo do Cocoapods 2
- [x] Implementação no Carthage 3

**Comment by ThiagoMiranda** [comment]
Link salvador da pátria
http://stackoverflow.com/questions/32730312/reason-no-suitable-image-found/32730393#32730393

**Comment by ThiagoMiranda** [comment]
Exemplos de outros SDKs:
**Brightcove**
http://docs.brightcove.com/en/perform/mobile-sdks/brightcove-player-sdk-for-ios/

**Ooyala**
http://support.ooyala.com/developers/documentation/tasks/mobile_sdk_ios_gettingstarted.html

**Comment by lzanol** [comment]
### Pendências

**CocoaPods**

Eliminar sub dependências mistas (libs estáticas + libs dinâmicas) ou contornar o erro.

**Comment by lzanol** [comment]
> If your containing app target links to an embedded framework, it must include the arm64 architecture or it will be rejected by the App Store.

https://developer.apple.com/library/prerelease/content/documentation/General/Conceptual/ExtensibilityPG/ExtensionScenarios.html

**Comment by lzanol** [comment]
### Instalação

http://stackoverflow.com/questions/12462385/unable-to-download-application-app-name-could-not-be-installed-at-this-time
