### ISSUE TITLE
Xcode 10.2 - Task failed with exit code 65 

### ISSUE THREAD

**Issue by dairan** [sambatech/player_sdk_ios#82]
carthage update --platform iOS dá erro  Xcode 10.2 - Task failed with exit code 65 

o log do erro está [aqui](https://gist.github.com/dairan/71e6144e93a4897f72b5bfe0c6fa7d41). 

Mas resumindo: error: SWIFT_VERSION '3.0' is unsupported, supported versions are: 4.0, 4.2, 5.0. (in target 'SambaPlayer')

**Comment by marquesm91** [comment]
@dairan a única forma que consegui fazer isso funcionar é instalar duas versões do Xcode (10.1 e 10.2) a versão 10.2 utilizo para meus projetos de freela e pessoais e a 10.1 fica encarregada apenas de rodar o Xcode para um App que utilizo esse SDK.

Esses passos podem te ajudar:

1. Para baixar o Xcode 10.1 eu entrei [aqui](https://developer.apple.com/download/more/).
2. Após baixar a versão 10.1, ela estará em um arquivo de extensão `.xip`. Clique duas vezes para descompactar e no final terá o `Xcode.app`.
3. Altere o nome para algo que lembre que é a versão antiga, por exemplo `Xcode10.1.app`.
4. Arraste o Xcode velho para a pasta Applications.
5. Agora no seu launcher terá o `Xcode` e `Xcode10.1`.
6. Entre no `Xcode10.1` e vá em `Xcode > Preferences > Locations` e altere o Command Line Tools para o Xcode 10.1. Faça isso para que utilize linhas de comando do Xcode velho caso precise.
7. Após isso, rode o build novamente que seu projeto compilará normalmente. 

Apenas quando resolverem atualizar para o Swift 4.0+ vamos conseguir utilizar o Xcode 10.2+ e deletar essa versão mais antiga.

Se eu soubesse melhor Swift e Objetice-C eu tentaria subir as versões e faria um PR, mas não tenho conhecimento pra isso.

Enquanto isso fico utilizando essa solução porca.

**Comment by dairan** [comment]
@marquesm91, estamos fazendo isso. Mas a questão que vai chegar um momento que a apple irá bloquear o envio com xcode 10.1. E como sei que nem sempre é simples fazer atualizações de frameworks, já abrir a assue, principalmente agora que teremos o Swift UI :D.

E muito obrigado pela resposta :)

**Comment by marquesm91** [comment]
@dairan Você tem toda razão. Enquanto isso, só nos resta rezar para que voltem a mexer nesse SDK e no SDK do Android.

**Comment by rangelvitor** [comment]
Pessoal, vou fechar a issue pois atualizamos a o sdk e segue nova release com atualização do swift para versão 4.2: https://github.com/sambatech/player_sdk_ios/releases/tag/2.1.0
